-- MySQL Script generated by MySQL Workbench
-- 2017. szept.  4., hétfő, 09:50:43 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema os_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema os_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `os_data` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `os_data` ;

-- -----------------------------------------------------
-- Table `os_data`.`projekts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`projekts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shortname` VARCHAR(45) NULL,
  `longname` VARCHAR(255) NULL,
  `begin` DATE NULL,
  `end` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`privileges` (
  `id` INT(2) NOT NULL,
  `privilege` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `szerep` INT(2) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_1_idx` (`szerep` ASC),
  CONSTRAINT `szerep`
    FOREIGN KEY (`szerep`)
    REFERENCES `os_data`.`privileges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT(500) NULL,
  `date` DATE NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `os_data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`presenters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`presenters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `title` VARCHAR(5) NULL,
  `organization` VARCHAR(255) NULL,
  `job` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(255) NULL,
  `shortname` VARCHAR(45) NULL,
  `place` VARCHAR(45) NULL,
  `format` TINYINT(1) NULL,
  `section_number` INT(11) NULL,
  `fejezet_number` INT(11) NULL,
  `language` TINYINT(1) NULL,
  `structure` TINYINT(1) NULL,
  `display` TINYINT(1) NULL,
  `tables` TINYINT(1) NULL,
  `links` TINYINT(1) NULL,
  `images` TINYINT(1) NULL,
  `projekts_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `presenters_id` INT NOT NULL,
  `checked_by` INT NOT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subjects_projekts1_idx` (`projekts_id` ASC),
  INDEX `fk_subjects_comments1_idx` (`comments_id` ASC),
  INDEX `fk_subjects_presenters1_idx` (`presenters_id` ASC),
  INDEX `fk_subjects_users1_idx` (`checked_by` ASC),
  CONSTRAINT `fk_subjects_projekts1`
    FOREIGN KEY (`projekts_id`)
    REFERENCES `os_data`.`projekts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `os_data`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_presenters1`
    FOREIGN KEY (`presenters_id`)
    REFERENCES `os_data`.`presenters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_users1`
    FOREIGN KEY (`checked_by`)
    REFERENCES `os_data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `number` INT(3) NULL,
  `subjects_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `checked_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_section_subjects1_idx` (`subjects_id` ASC),
  INDEX `fk_section_comments1_idx` (`comments_id` ASC),
  INDEX `fk_sections_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_section_subjects1`
    FOREIGN KEY (`subjects_id`)
    REFERENCES `os_data`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_section_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `os_data`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `os_data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`subsections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`subsections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `number` INT(3) NULL,
  `section_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `checked_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subsection_section1_idx` (`section_id` ASC),
  INDEX `fk_subsection_comments1_idx` (`comments_id` ASC),
  INDEX `fk_subsections_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_subsection_section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `os_data`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subsection_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `os_data`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subsections_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `os_data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `os_data`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`videos` (
  `id` INT(11) NOT NULL,
  `filename` VARCHAR(45) NULL,
  `link` VARCHAR(150) NULL,
  `size` INT(10) NULL,
  `length` INT(11) NULL,
  `title` VARCHAR(200) NULL,
  `dimension` VARCHAR(45) NULL,
  `format` VARCHAR(5) NULL,
  `start_screen` TINYINT(1) NULL,
  `subtitle` TINYINT(1) NULL,
  `end_screen` TINYINT(1) NULL,
  `transition` TINYINT(1) NULL,
  `performer_errors` TINYINT(1) NULL,
  `subsection_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `checked_by` INT NULL,
  `created_by` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Videos_subsection1_idx` (`subsection_id` ASC),
  INDEX `fk_Videos_comments1_idx` (`comments_id` ASC),
  CONSTRAINT `fk_Videos_subsection1`
    FOREIGN KEY (`subsection_id`)
    REFERENCES `os_data`.`subsections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videos_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `os_data`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`animations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`animations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `style` TINYINT(1) NULL,
  `clean` TINYINT(1) NULL,
  `instructions` TINYINT(1) NULL,
  `timing` TINYINT(1) NULL,
  `is_correct_clean` TINYINT(1) NULL,
  `replies` TINYINT(1) NULL,
  `restartable` TINYINT(1) NULL,
  `subsection_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `checked_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_animations_subsection1_idx` (`subsection_id` ASC),
  INDEX `fk_animations_comments1_idx` (`comments_id` ASC),
  INDEX `fk_animations_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_animations_subsection1`
    FOREIGN KEY (`subsection_id`)
    REFERENCES `os_data`.`subsections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animations_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `os_data`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animations_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `os_data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`replies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT(500) NULL,
  `date` DATE NULL,
  `comments_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_replies_comments1_idx` (`comments_id` ASC),
  CONSTRAINT `fk_replies_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `os_data`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `format` TINYINT(1) NULL,
  `style` TINYINT(1) NULL,
  `links` TINYINT(1) NULL,
  `images` TINYINT(1) NULL,
  `file_name_correct` TINYINT(1) NULL,
  `page_number` TINYINT(1) NULL,
  `align` TINYINT(1) NULL,
  `headers_footers` TINYINT(1) NULL,
  `subsection_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `checked_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pdf_subsection1_idx` (`subsection_id` ASC),
  INDEX `fk_pdf_comments1_idx` (`comments_id` ASC),
  INDEX `fk_documents_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_pdf_subsection1`
    FOREIGN KEY (`subsection_id`)
    REFERENCES `os_data`.`subsections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pdf_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `os_data`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documents_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `os_data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`quiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `format` TINYINT(1) NULL,
  `subsection_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `is_pass` TINYINT(1) NULL,
  `is_time` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quiz_subsection1_idx` (`subsection_id` ASC),
  INDEX `fk_quiz_comments1_idx` (`comments_id` ASC),
  INDEX `fk_quiz_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_quiz_subsection1`
    FOREIGN KEY (`subsection_id`)
    REFERENCES `os_data`.`subsections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `os_data`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `os_data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_data`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_data`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `is_right_answer` TINYINT(1) NULL,
  `is_clear` TINYINT(1) NULL,
  `is_spelling_correct` TINYINT(1) NULL,
  `is_same_format` TINYINT(1) NULL,
  `is_code` TINYINT(1) NULL,
  `is_list_number` TINYINT(1) NULL,
  `quiz_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `checked_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_quiz1_idx` (`quiz_id` ASC),
  INDEX `fk_questions_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_questions_quiz1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `os_data`.`quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `os_data`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
